// peggy.d.ts

declare module "peggy" {

    export interface SyntaxError {
        expected: unknown[];
        found: string;
        location: Location;
        name: string;
    }

    export interface Location {
        start: Position;
        end: Position;
        source?: unknown;
    }

    export interface Position {
        line: number;
        column: number;
        offset: number;
    }

    // Declare the parser function or object that's typically generated by peggy
    export const parse: (input: string, options?: Record<string, unknown>) => unknown;
}

